// <auto-generated />
using System;
using MascotasASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MascotasASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250413035828_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MascotasASP.Models.AsignacionPaseos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int");

                    b.Property<int?>("IdMascota")
                        .HasColumnType("int");

                    b.Property<string>("Paseador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("horarioId")
                        .HasColumnType("int");

                    b.Property<int>("mascotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("horarioId");

                    b.HasIndex("mascotaId");

                    b.ToTable("AsignacionPaseos");
                });

            modelBuilder.Entity("MascotasASP.Models.DueñosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Duenos");
                });

            modelBuilder.Entity("MascotasASP.Models.HorariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("MascotasASP.Models.MascotaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("MetrosId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("MascotasASP.Models.MetrosCuadradosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Metros")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MetrosCuadrados");
                });

            modelBuilder.Entity("MascotasASP.Models.ReporteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comportamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paseador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("asignacionId")
                        .HasColumnType("int");

                    b.Property<int>("idAsignacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("asignacionId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("MascotasASP.Models.AsignacionPaseos", b =>
                {
                    b.HasOne("MascotasASP.Models.HorariosModel", "horario")
                        .WithMany()
                        .HasForeignKey("horarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MascotasASP.Models.MascotaModel", "mascota")
                        .WithMany()
                        .HasForeignKey("mascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("horario");

                    b.Navigation("mascota");
                });

            modelBuilder.Entity("MascotasASP.Models.MascotaModel", b =>
                {
                    b.HasOne("MascotasASP.Models.DueñosModel", "Dueño")
                        .WithMany()
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MascotasASP.Models.MetrosCuadradosModel", "Metros")
                        .WithMany()
                        .HasForeignKey("MetrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Metros");
                });

            modelBuilder.Entity("MascotasASP.Models.ReporteModel", b =>
                {
                    b.HasOne("MascotasASP.Models.AsignacionPaseos", "asignacion")
                        .WithMany()
                        .HasForeignKey("asignacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asignacion");
                });
#pragma warning restore 612, 618
        }
    }
}
